# Generated by Django 5.1 on 2024-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50, verbose_name='Comment text')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Comment date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=150, verbose_name='Desription')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Date of creation')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
